-- setup with all defaults
-- each of these are documented in `:help nvim-tree.OPTION_NAME`
-- require'nvim-tree'.setup { -- BEGIN_DEFAULT_OPTS
--    -- 关闭文件时自动关闭
--     auto_close = true,
-- } -- END_DEFAULT_OPTS